PR_SMTP_ADDRESS = "http://schemas.microsoft.com/mapi/proptag/0x39FE001E"
PR_SENDER_SMTP_ADDRESS = "http://schemas.microsoft.com/mapi/proptag/0x5D01001F"
PR_MEETING_SENDER_SMTP_ADDRESS = "http://schemas.microsoft.com/mapi/proptag/0x5D0A001F"
PR_SENT_REPRESENTING_SMTP_ADDRESS = "http://schemas.microsoft.com/mapi/proptag/0x5D02001F"
PR_LAST_MODIFIER_NAME_W = "http://schemas.microsoft.com/mapi/proptag/0x3FFA001F"
PR_SENT_REPRESENTING_EMAIL_ADDRESS_W = "http://schemas.microsoft.com/mapi/proptag/0x0065001F"
